### ISSUE TITLE
请求支持arm架构

### ISSUE THREAD

**Issue by leilei542** [ikrong/sync-docker-image#1]
能否支持拉取arm架构的 毕竟很多苹果，物联网用户

**Comment by ikrong** [comment]
action 使用的是 skopeo 来同步镜像，是支持多架构的。但是对镜像中manifest版本的处理还有些问题，部分多架构可能会失败。

**Comment by ikrong** [comment]
> 能否支持拉取arm架构的 毕竟很多苹果，物联网用户

是运行环境里的skopeo版本太低了，升级了一下版本，现在应该是能够正常同步了
