### ISSUE TITLE
when I use sync.yml. I find a problem

### ISSUE THREAD

**Issue by liangxiong3403** [ikrong/sync-docker-image#2]
![image](https://github.com/ikrong/sync-docker-image/assets/27960242/5527b347-bdd2-4596-9bbf-b077ed11d560)
what can i do to fix it?

**Comment by ikrong** [comment]
My mistake, thank you for pointing it out. I have fixed it, please try again.

**Comment by liangxiong3403** [comment]
Great! thanks a lot.
