### ISSUE TITLE
能否在工作流列表上面显示同步的镜像名称。

### ISSUE THREAD

**Issue by yibohub** [ikrong/sync-docker-image#3]
![image](https://github.com/ikrong/sync-docker-image/assets/161293070/26e89ff9-6e1b-4d9e-88b4-a1665f3c8332)
要同步的镜像多了后从工作流列表上面无法区分是哪个镜像。不方便管理。

**Comment by ikrong** [comment]
这个列表是github的页面，无法自定义，没办法展示更多信息。

**Comment by ikrong** [comment]
> ![image](https://private-user-images.githubusercontent.com/161293070/343621783-26e89ff9-6e1b-4d9e-88b4-a1665f3c8332.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3NjkyMDIsIm5iZiI6MTcyMDc2ODkwMiwicGF0aCI6Ii8xNjEyOTMwNzAvMzQzNjIxNzgzLTI2ZTg5ZmY5LTZlMWItNGQ5ZS04OGI0LWExNjY1ZjNjODMzMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxMlQwNzIxNDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01Y2UwNWU4ZGUxYjgxZTBmMmMxMDY3OGY2YThiMTEwODBjYmQ2NTdkZDYyMTJmMjI2YTM4YTFkYjFhNzg0YjJlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.GQeuJPGk6iZsnFA3HRggqtc53rZihFPGugE8lp0Pc90) 要同步的镜像多了后从工作流列表上面无法区分是哪个镜像。不方便管理。

之前文档没看仔细，今天看到是支持设置的，现在运行任务，这里列表将会展示操作的镜像
