### ISSUE TITLE
用sync同步镜像报错

### ISSUE THREAD

**Issue by yuqilin-github** [ikrong/sync-docker-image#6]
请教大佬，用sync同步mysql镜像时报错内容：
denied: unknown manifest class for application/octet-stream
![61db0f6a0ea1bbce29db7a7de564893](https://github.com/user-attachments/assets/864bb335-5e28-4865-ab90-3d38c852a3a7)

**Comment by ikrong** [comment]
这个版本的镜像是很久之前的docker构建的，其manifest media type类型有问题，不能直接同步，可能需要对镜像进行转换才可以，目前我还没有支持，你可以先用其他标签或者其他工具。

**Comment by yuqilin-github** [comment]
了解，感谢解答
