### ISSUE TITLE
SOURCE_CREDENTIAL是什么，需要填写吗

### ISSUE THREAD

**Issue by ytanck** [ikrong/sync-docker-image#8]

**Comment by ikrong** [comment]
镜像源 (Registry)的账号和密码是 SOURCE_CREDENTIAL

目标源 (Registry)的账号和密码是 DESTINATION_CREDENTIAL

目标源账号和密码(DESTINATION_CREDENTIAL)必填，镜像源账号和密码(SOURCE_CREDENTIAL)非必填

不过由于docker.io对非登录状态请求次数有限制，所以最好是填写。

**Comment by ytanck** [comment]
SOURCE_CREDENTIAL格式也是username:password吗

**Comment by ikrong** [comment]
嗯嗯，是的，和 DESTINATION_CREDENTIAL 格式一致
